spring.application.name=sports-marketplace
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/sports-marketplace
spring.datasource.username=postgres
spring.datasource.password=user

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create

jwt.secretKey=tralaleroTralala$$$bombardiloCrocodilo