spring.datasource.url=jdbc:postgresql://localhost:5432/sports-marketplace
spring.datasource.username=postgres
spring.datasource.password=user
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secretKey=ultra6$mega99$$strong521$$$uncrackable7002$$$$secretKEY
jwt.expirationMs=3600000

server.port=8080